version: '3'
services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    image: farahoum123/employee-overtime-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=employee_db
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    image: farahoum123/employee-overtime-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=employee_db
    volumes:
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql